useDotenv: true

service: s3-watch-lambda
frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin
  - serverless-ignore
  - serverless-deployment-bucket
  - serverless-plugin-tracing
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "*"

  # Versioning Deployed Functions
  # https://www.serverless.com/framework/docs/providers/aws/guide/functions#versioning-deployed-functions
  versionFunctions: false

  # lambda deployment bucket name
  deploymentBucket:
    name: ${self:service}-deployment-bucket-${self:provider.stage}
    serverSideEncryption: AES256

package:
  individually: true
  # package.json devDependencies are not included in the deployment package
  excludeDevDependencies: true
  exclude:
    - ./**
  include:
    - ./src/**

functions:
  S3WatchHandler:
    handler: src/v1/handlers/s3watch.lambda_handler
    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*
          existing: true
          forceDeploy: true
